### ISSUE TITLE
Use the twitter API's search function to search for a hashtag

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#1]
Hi Yuliya,
We will use Github for tracking the assignments and their related issues.
Yesterday's assignment was to use twitter api to search for hashtags.
Assignment:
- Use help(twitter) in the terminal to see how to search for a hashtag.
- Write a new program in a new file to search for the following hashtags:
    1) **Apollo11**
    2) **Fashion**
- Print the type of search result
- Based on the type of the search result (list or dict), iterate through the results and print them in a human readable form.
- Checkin the new program into Github.

Z
( @yuliaua1 )

**Comment by ghost** [comment]
@yuliaua1 Created a project and added this assignment to the project.

**Comment by ghost** [comment]
@yuliaua1 Created a project and a milestone (due this Sunday) for this specific assignment.

**Comment by yuliaua1** [comment]
I am working on the first draft of the program where I will have to connect to the Twitter API. In progress...

**Comment by ghost** [comment]
Hi, Any update on the status of this task? :) 
Thanks!

**Comment by yuliaua1** [comment]
Please review committed file. I have used pprint module for the readability. Thanks!

**Comment by yuliaua1** [comment]
Reopening for the review

**Comment by ghost** [comment]
@yuliaua1  The code is functioning as expected and is pretty printing the whole results.
Looking at the output of pprint we see that the dictionary has a key called **'user'** which is a dictionary. _(remember we used pprint to examine the data, so that later on we can do something useful with it)_
One of the keys in the **'user'** dictionary is description.
## Assignment extension: 
Print the value for the key  **'description'** in the **'user'** dictionary for  both hashtags _#Apollo11_ and _#Fashion_

**Comment by yuliaua1** [comment]
@aakazemaa Questions: since dictionary 'user' is the element in the list 'statuses', how do i access the key of the dictionary if it is a part of the list? 
I have tried to use 
for key, value in e['user']:
    print(key)
But it gave me an error. ValueError: too many values to unpack

**Comment by ghost** [comment]
@yuliaua1 Please note that in order to iterate through a dictionary, we must call iteritems() on it .

**so instead of:**

`for key, value in e['user']:`

**use:**

`for key, value in e['user'].iteritems():`

**Comment by yuliaua1** [comment]
Please see updated code with correct statement for iteration through the dictionary 'user'

**Comment by ghost** [comment]
@yuliaua1 I do not see the 'description' output in your code.
Your code is only printing the keys!!!
The assignment says:

Assignment extension:
Print the value for the key 'description' in the 'user' dictionary for both hashtags #Apollo11 and #Fashion

**Comment by yuliaua1** [comment]
@aakazemaa Completed the assignment in accordance with the spec. The code is ready for the review. Thanks.

**Comment by ghost** [comment]
@yuliaua1 The code is **functioning as expected**, fetching the descriptions of the users retrieved from Twitter API.
