### ISSUE TITLE
Create MasterCode UILable and fill it up with random arrangement of 4 marbles.

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#10]
Add a UILabel to the Interface. Call it masterCode (wire it as an outlet to the viewController)
Program the 'newGame' Action to set the text of masterCode to a random arrangement of marbles.
Hint:
Inside 'newGame' action define the following array:
let marbles = ["🔴","🔵", "⚫️", "⚪️"]
Then randomly choose an element from this array and concatenate it to masterCode.text.

**Comment by yuliaua1** [comment]
Updated code Create MasterCode UILable and filled it up with random arrangement of 4 marbles. Note, marbles appear in the label as a list ( "🔴","🔵", "⚫️", "⚪️"), need assistance in updating code to display marbles correctly w/o "" and comas.Please review.

**Comment by ghost** [comment]
When a marble from the array `marbles = ["🔴","🔵", "⚫️", "⚪️"]`  is chosen, then it needs to get concatenated to the UILabel's text.
For example:
`masterCode.text = masterCode.text! + marbles[1]`
Please feel free to ask question if this is still not clear.

**Comment by yuliaua1** [comment]
Included randomly selected marbles into the string and displayed them in the UILable. Please review

**Comment by ghost** [comment]
Program is functioning as expected.
