### ISSUE TITLE
Program "Check" buttons to determine if the guess row matches the masterCode

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#11]
1. Please program the "Check" buttons to determine if their corresponding guess row is matching the `masterCode.text!` UILabel. After a "Check" button is pushed its corresponding row should be printed in the console. (based on the screenshot)
2. Please change the masterCode UILabel's appearance in accordance with the attached screenshot.
![screen shot 2017-10-06 at 6 21 56 am](https://user-images.githubusercontent.com/9558343/31280402-1a5fba22-aa61-11e7-9297-4349d06a0f02.png)

**Comment by yuliaua1** [comment]
Updated code to program Check button  and MasterCode UI Label background as requested.

**Comment by ghost** [comment]
program is functioning as expected.
