### ISSUE TITLE
Program the 'checkMe' to show a graphical hint to the user.

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#12]
Please program the `'checkMe' `Action so that when a check button is pushed, its label's text shows a hint as depicted in the screenshot below.
![simulator screen shot - iphone 6 - 2017-10-08 at 14 45 00](https://user-images.githubusercontent.com/9558343/31321246-a2610dfe-ac37-11e7-9764-0807924a2586.png)

**Comment by yuliaua1** [comment]
Updated code in relation to assignment 11. Added code to alert end user about the incomplete row.

**Comment by ghost** [comment]
Program is functioning as expected and is giving the correct hint to the user based on the game's logic.
