### ISSUE TITLE
Write a program calculate the sum of numbers in a list and print it on the console

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#2]
This assignment is to:

- create a list of random numbers between 1 to 20
- Size of the list is 10
- print the list
- print the sum of numbers
- write the program as **_listSum.py_** and check in to _github_.

_Note: we are at the same time practicing working with github_

**Comment by yuliaua1** [comment]
@aakazemaa please review my program for the Assignment 2.

**Comment by ghost** [comment]
The program is functioning in accordance with the spec.
Additional features for this program will be assigned separately. Closing the issue.
