### ISSUE TITLE
Write a function to reverse a list of numbers.

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#4]
Write a program to

- Generate a list of size 10 whose elements are random numbers between 1 to 100.
- Write a function to take this list as a parameter. 
- This function should return another list which contains the **reversed** order of our original list.
- Print the original list and its reversed list.

**Comment by yuliaua1** [comment]
Hi,
Please see committed code with the def function that reverses original list.
Thanks,
Yuliya

**Comment by ghost** [comment]
@yuliaua1  Hi, As discussed, although the proposed algorithm is correct, it is not the solution to the stated problem. The problem statement explicitly is asking for returning (not printing) a new list, which its elements are in the reversed order of the original list. Therefore, we eventually will have two lists.

**Comment by yuliaua1** [comment]
Hi, please see updated code with the reverse list. Thank you.

**Comment by ghost** [comment]
@yuliaua1  The code is functioning correctly, however, we want instead of calling reverselist() inside the print(), store the returned value from reverselist() in a variable. 
This way we can print it and use it for carrying out other business logic further down in the program. 

1) Please change the code accordingly and print both lists at the end of program:
For example:
`print(originalList)`
`print(reversedList)`
2) Also, please use appropriate names for the variables, instead of generic names, so that other programmers can find out what the variable is pointing to easily.

**Comment by yuliaua1** [comment]
@aakazemaa Hi, please see attached updated code where I have stored the returned value from reverselist() in a variable. Thank you. Yuliya

**Comment by ghost** [comment]
@yuliaua1 Thank you for the note. 
1) lease **change the name** of the 'ModifiedList' to a name which corresponds to the nature of modification (in this case reversed).
2) Please **print the original list** at the end of the program as stated above.
Thank you.

**Comment by yuliaua1** [comment]
@aakazemaa  Updated ReverseList.py with the correct list names and printed lists according to the spec.

**Comment by ghost** [comment]
@yuliaua1 Thank you. The code is in **compliance** with the **specification**.
