### ISSUE TITLE
Find the number of occurrences of elements in a list of random lowercase letters

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#5]
Write a program to:

- Create a list of size 20
- Each element in this list is a random ascii_lowercase letter
- Calculate the number of occurrences of each letter in this list.
- Print those letters which have occurred only **once**.

For example the output of your program should look like this:
`['f', 'i', 'g', 'n', 'g', 'b', 'd', 'b', 'n', 't', 'q', 's', 'p', 'z', 'k', 'd', 'q', 's', 'q', 'g']`
`
f
i
k
p
t
z`

**Comment by ghost** [comment]
@yuliaua1 Assignment #5 
### Counting Occurrences of Elements in a List

**Comment by ghost** [comment]
@yuliaua1 Did you get the notification?

**Comment by yuliaua1** [comment]
@aakazemaa . RadomLetters file is modified in accordance with the spec. Question - Right now the letters that occurred once are printed in column. I am in progress of researching on how to print them in the line. Any advise? Thanks!

**Comment by ghost** [comment]
@yuliaua1 The program is correct and in compliance with the specification except the output part.
Answer to the question:
The easiest way is to define a string variable and concatenate the _key_ to it, and in the end print the i.e.
`outputStr = outputStr + " " + str(key)`
Please complete the program. Thanks.

**Comment by yuliaua1** [comment]
@aakazemaa . RadomLetters file is modified in accordance with the spec. Printed results into the list in order to display them in one line. Please review.

**Comment by ghost** [comment]
@yuliaua1 The output of the program is not in compliance with the spec.
The program is printing:
`['a', 'b', 'e', 'd', 'n', 's']>>>>>> letters occurring one time.`
But the spec says it should print:
`a b e d n s`

**Please rewrite the program to function as specified in the spec.**

**Comment by ghost** [comment]
@yuliaua1 What is the status on this issue? The code in github is still printing:
`['a', 'b', 'e', 'd', 'n', 's']>>>>>> letters occurring one time.`
Expected output from print() funtion:
`a b e d n s`

**Comment by ghost** [comment]
closing the issue due to change of project to swift and iOS. This issue will be transferred to iOS.
