### ISSUE TITLE
Write a program to shuffle the elements of a list.

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#6]
Having a list of elements (character, numbers, etc.), write a program to shuffle the elements of the list.
For example if the original list is:
`['a', 'b', 'c', 'd', 'e']`

The program should generate a new list which has shuffled the elements of the original list in a an **arbitrary order**. 
`['d', 'b', 'e', 'a', 'c']`
or 
`['d', 'e', 'b', 'c', 'a']` 
etc...

**Comment by yuliaua1** [comment]
@aakazemaa RundomShuffleList is prepared using random.shuffle method. Please review.

**Comment by ghost** [comment]
@yuliaua1 The program is shuffling the list as expected. 
However, your program is shuffling 5 times. We only need to shuffle one time. **Please rewrite the program to shuffle only once.**

**Comment by yuliaua1** [comment]
@aakazemaa I have rewritten the program to shuffle only one time. Thank you.

**Comment by ghost** [comment]
@yuliaua1 program is working as expected. closing.
