### ISSUE TITLE
Program the 'New Game' button to change the guess buttons.

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#8]
Please program the 'New Game' button to change the guess buttons' texts to red apple emoji  **except** for the **'Check' buttons** according to the attached screenshot.
![screen shot 2017-10-02 at 4 24 41 pm](https://user-images.githubusercontent.com/9558343/31103918-9ad95134-a78e-11e7-9c23-fb943eb8d74b.png)

**Comment by yuliaua1** [comment]
Programmed NewGame button to change the guess buttons' texts to red apple emoji except for the 'Check' buttons as requested.

**Comment by ghost** [comment]
Thanks! The issue is resolved.
