### ISSUE TITLE
Program the 'CheckMe' Actions to change the buttons' texts of its corresponding row.

### ISSUE THREAD

**Issue by ghost** [yuliaua1/algorithms#9]
Please program the _'CheckMe'_ Action (which gets fired when we push any guess buttons) so that, when we push the **'Check' button**, then the texts in the corresponding buttons of its row change to green apple as shown in the picture below.

![simulator screen shot - iphone 6 - 2017-10-03 at 16 25 11](https://user-images.githubusercontent.com/9558343/31153885-6c60308c-a858-11e7-897b-3aa45529171f.png)

**Comment by yuliaua1** [comment]
Programmed in according to the assignment. Please review.

**Comment by ghost** [comment]
program is working as expected.
